export const Colors = {
    dark: {
        primary: "#7C4DFF",
        secondary: "#26A69A",
        warning: "#FF7043",
        link: "#82B1FF",
        text: "#E0E0E0",
        title: "#FFFFFF",
        background: "#121212",
        navBackground: "#1C1C1C",
        iconColor: "#B39DDB",
        iconColorFocused: "#FFFFFF",
        uiBackground: "#1E1E1E",
        cardBackground: "#242424",
        shadow: "#000000",
        border: "#333333",
        buttonBackground: "#7C4DFF",
    },

    light: {
        primary: "#7C4DFF",
        secondary: "#26A69A",
        warning: "#FF7043",
        link: "#2962FF",
        text: "#212121",
        title: "#000000",
        background: "#FFFFFF",
        navBackground: "#E8EAF6",
        iconColor: "#7C4DFF",
        iconColorFocused: "#311B92",
        uiBackground: "#FAFAFA",
        cardBackground: "#F5F5F5",
        shadow: "#BDBDBD",
        border: "#E0E0E0",
        buttonBackground: "#7C4DFF",
    },
};