export const Colors = {
    dark: {
        primary: "#4A90E2",
        secondary: "#4CAF50",
        warning: "#E94E77",
        link: "#64B5F6",
        text: "#ECEFF1",
        title: "#FFFFFF",
        background: "#121212",
        navBackground: "#1E1E1E",
        iconColor: "#90CAF9",
        iconColorFocused: "#FFFFFF",
        uiBackground: "#1F1F1F",
        cardBackground: "#292929",
        shadow: "#000000",
        border: "#333333",
        buttonBackground: "#4A90E2",
        accent: "#7CA7FF",
        profileBackground: "#0E0E12",
        profileIcon: "#CCCCCC",
        surface: "#000000",
        mutedText: "#A0A0A0",
        backHome: "#ffffffff",
        postText: "#E3F2FD"
    },

    light: {
        primary: "#4A90E2",
        secondary: "#4CAF50",
        warning: "#E94E77",
        link: "#1E88E5",
        text: "#212121",
        title: "#000000",
        background: "#FAFAFA",
        navBackground: "#E3F2FD",
        iconColor: "#4A90E2",
        iconColorFocused: "#0D47A1",
        uiBackground: "#FFFFFF",
        cardBackground: "#F5F5F5",
        shadow: "#CCCCCC",
        border: "#DDDDDD",
        buttonBackground: "#4A90E2",
        accent: "#7B9DFF",
        profileBackground: "#FAFAFA",
        profileIcon: "#343434",
        surface: "#FFFFFF",
        mutedText: "#5F5F5F",
        backHome: "#464646ff",
        postText: "#E3F2FD"
    },
};
